# Generated by Django 5.2.3 on 2025-06-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_flow_app', '0002_patientprofile_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Cardiologist', 'Cardiologist'), ('Nurse', 'Nurse'), ('Sonographer', 'Sonographer'), ('Administrative Staff', 'Administrative Staff'), ('Patient', 'Patient'), ('Group Manager', 'Group Manager'), ('IT Staff', 'IT Staff'), ('General Practitioner', 'General Practitioner')], max_length=20),
        ),
    ]
