# Generated by Django 5.2.3 on 2025-06-17 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_flow_app', '0002_appointment_patientprofile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profileuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='CardiologistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('emergency_contact', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=55)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'Patient'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
