# Generated by Django 5.2.3 on 2025-06-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_flow_app', '0003_alter_profileuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiologistprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cardiologistprofile',
            name='country',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='country',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
