# Generated by Django 5.2.3 on 2025-06-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_flow_app', '0004_cardiologistprofile_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
