# Generated by Django 5.2.3 on 2025-06-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_flow_app', '0005_profileuser_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='otp',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
