# Generated by Django 5.2.3 on 2025-06-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_flow_app', '0006_remove_profileuser_otp_profileuser_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
